// Code generated by xgen. DO NOT EDIT.

using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace schema
{
	// MyType2 ...
	[GeneratedCode("xgen", null)]
	[XmlType("myType2")]
	public partial class MyType2
	{
		[XmlAttribute("length")] public int? LengthAttr { get; set; }
		[XmlText(typeof(byte[]))] public byte[]? Value { get; set; }
	}

	// MyType3 ...
	[GeneratedCode("xgen", null)]
	[XmlType("myType3")]
	public partial class MyType3
	{
		[XmlAttribute("length")] public int? LengthAttr { get; set; }
		[XmlText(typeof(DateOnly))] public DateOnly? Value { get; set; }
	}

	// MyType4 ...
	[GeneratedCode("xgen", null)]
	[XmlType("myType4")]
	public partial class MyType4
	{
		[XmlElement("title")] public string Title { get; set; } = "";
		[XmlElement("blob")] public byte[] Blob { get; set; } = Array.Empty<byte>();
		[XmlElement("timestamp")] public DateTime Timestamp { get; set; }
	}

	// MyType6 ...
	[GeneratedCode("xgen", null)]
	[XmlType("MyType6")]
	public partial class MyType6
	{
		[XmlAttribute("code")] public string? CodeAttr { get; set; }
		[XmlAttribute("identifier")] public int? IdentifierAttr { get; set; }
	}

	// MyType7 ...
	[GeneratedCode("xgen", null)]
	[XmlType("MyType7")]
	public partial class MyType7
	{
		[XmlAttribute("origin")] public string OriginAttr { get; set; } = "";
		[XmlText(typeof(string))] public string? Value { get; set; }
	}

	// MyType8 ...
	[GeneratedCode("xgen", null)]
	[XmlType("MyType8")]
	public partial class MyType8
	{
		[XmlElement("code")] public string? CodeAttr { get; set; }
		[XmlAttribute("identifier")] public int? IdentifierAttr { get; set; }
	}

	// TopLevel ...
	[GeneratedCode("xgen", null)]
	[XmlType("TopLevel")]
	public partial class TopLevel : MyType6 
	{
		[XmlAttribute("cost")] public double? CostAttr { get; set; }
		[XmlAttribute("LastUpdated")] public DateTime? LastUpdatedAttr { get; set; }
		[XmlElement("nested")] public MyType7 Nested { get; set; } = new();
		[XmlElement("myType1")] public List<byte[]> MyType1 { get; set; } = new();
		[XmlElement("myType2")] public List<MyType2> MyType2 { get; set; } = new();
	}
}
